name: Gravitee.io APIM
description: |
  Gravitee.io - Open Source API Management
version: latest
category: API Management
licence : Apache Licence, version 2
maintainer: Nicolas Geraud <nicolas.geraud@graviteesource.com>
projectURL: https://gravitee.io
