#-------------------------------------------------------------------------------
# Copyright (C) 2018 The Gravitee team (http://gravitee.io)
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#            http://www.apache.org/licenses/LICENSE-2.0
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#-------------------------------------------------------------------------------

gateway:
  image: graviteeio/gateway:${gravitee_version}
  hostname: gateway
  external_links:
    - ${mongodb_service}:mongodb
    - ${es_service}:elasticsearch
  environment:
    - gravitee_management_mongodb_dbname=gravitee
    - gravitee_management_mongodb_host=mongodb
    - gravitee_management_mongodb_port=27017
    - gravitee_reporters_elasticsearch_endpoints=http://elasticsearch:9200
  labels:
    io.rancher.container.pull_image: always
    
management-api:
  image: graviteeio/management-api:${gravitee_version}
  hostname: management-api
  external_links:
    - ${mongodb_service}:mongodb
    - ${es_service}:elasticsearch
  environment:
    - gravitee_management_mongodb_dbname=gravitee
    - gravitee_management_mongodb_host=mongodb
    - gravitee_management_mongodb_port=27017
    - gravitee_analytics_elasticsearch_endpoints=http://elasticsearch:9200
  labels:
    io.rancher.container.pull_image: always

management-ui:
  hostname: management-ui
  image: graviteeio/management-ui:${gravitee_version}
  environment:
    - MGMT_API_URL=http://${management_api_host}:${management_api_port}/management/
  labels:
    io.rancher.container.pull_image: always

loadbalancer:
  ports:
  - ${management_api_port}:8083
  - ${management_ui_port}:80
  - ${gateway_port}:8082
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.loadbalancer.target.management-api: ${management_api_port}=8083
    io.rancher.loadbalancer.target.management-ui: ${management_ui_port}=80
    io.rancher.loadbalancer.target.gateway: ${gateway_port}=8082
  tty: true
  image: rancher/load-balancer-service
  links:
  - management-ui:management-ui
  - management-api:management-api
  - gateway:gateway   