version: '2'

catalog:
  name: Gravitee.io
  version: 1.0-rancher1
  description: |
    Gravitee.io API Management.
  maintainer: "Nicolas Geraud <nicolas.geraud@graviteesource.com>"
  uuid: graviteeio-apim-0

  questions:
    - variable: "gravitee_version"
      description: |
        allowed values : latest, 1.12.5, 1.13.0, ... .
        See https://hub.docker.com/r/graviteeio/gateway/tags/ to have the full list of tags.
      label: "Gravitee.io APIM version"
      required: true
      default: "latest"
      type: "string"

    - variable: "gateway_port"
      description: |
        The Gravitee.io APIM Gateway port.
      label: "Public Gateway port"
      required: true
      default: "8002"
      type: "int"

    - variable: "management_ui_port"
      description: |
        The Gravitee.io APIM UI port.
      label: "Management UI port"
      required: true
      default: "8000"
      type: "int"

    - variable: "management_api_port"
      description: |
        The Gravitee.io APIM API port"
      label: "Management API port"
      required: true
      default: "8001"
      type: "int"

    - variable: "management_api_host"
      description: "Public Management API Hostname or IP (Your rancher host node)"
      label: "Public Management API Host"
      required: true
      default: "localhost"
      type: "string"

    - variable: "mongodb_service"
      description: |
        Choose the MongoDB service to use.
      label: "MongoDB stack/service"
      default: ""
      required: true
      type: "service"

    - variable: "es_service"
      description: |
        Choose the Elasticsearch service to use.
        WARNING: versions > 5 are not supported.
      label: "Elasticsearch stack/service"
      default: ""
      required: true
      type: "service"

services:
  gateway:
    scale: 1
    health_check:
      port: 18082
      interval: 2000
      initializing_timeout: 60000
      unhealthy_threshold: 3
      strategy: recreate
      healthy_threshold: 2
      response_timeout: 2000

  management-api:
    scale: 1
    health_check:
      port: 18083
      interval: 2000
      initializing_timeout: 60000
      unhealthy_threshold: 3
      strategy: recreate
      healthy_threshold: 2
      response_timeout: 2000

  management-ui:
    scale: 1
    health_check:
      port: 8000
      interval: 2000
      initializing_timeout: 60000
      unhealthy_threshold: 3
      strategy: recreate
      healthy_threshold: 2
      response_timeout: 2000

  loadbalancer:
    load_balancer_config:
      haproxy_config: {}
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
